/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SpotifyPlayerRouteImport } from './routes/spotify-player'
import { Route as SpotifyCallbackRouteImport } from './routes/spotify-callback'
import { Route as SongsRouteImport } from './routes/songs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchichtplanRouteImport } from './routes/schichtplan'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as MusikRouteImport } from './routes/musik'
import { Route as MitarbeiterRouteImport } from './routes/mitarbeiter'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsSpotifyRouteImport } from './routes/settings.spotify'
import { Route as SettingsRegionRouteImport } from './routes/settings.region'
import { Route as SettingsRecipesRouteImport } from './routes/settings.recipes'
import { Route as SettingsQrRouteImport } from './routes/settings.qr'
import { Route as SettingsProductsRouteImport } from './routes/settings.products'
import { Route as SettingsPrintersRouteImport } from './routes/settings.printers'
import { Route as SettingsMembersRouteImport } from './routes/settings.members'
import { Route as SettingsLocationsRouteImport } from './routes/settings.locations'
import { Route as SettingsHappyHourRouteImport } from './routes/settings.happy-hour'
import { Route as SettingsDatabaseRouteImport } from './routes/settings.database'
import { Route as OrderTokenRouteImport } from './routes/order.$token'
import { Route as OrderTokenPaidRouteImport } from './routes/order.$token.paid'
import { Route as ApiPublicSpotifySearchRouteImport } from './routes/api/public/spotify-search'
import { Route as ApiPublicSongRequestRouteImport } from './routes/api/public/song-request'
import { Route as ApiPublicServiceCallRouteImport } from './routes/api/public/service-call'
import { Route as ApiPublicPaymentRequestRouteImport } from './routes/api/public/payment-request'
import { Route as ApiPublicOrderRouteImport } from './routes/api/public/order'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicTableTokenRouteImport } from './routes/api/public/table.$token'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsCreateTableCheckoutRouteImport } from './routes/api/public/payments/create-table-checkout'

const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotifyPlayerRoute = SpotifyPlayerRouteImport.update({
  id: '/spotify-player',
  path: '/spotify-player',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotifyCallbackRoute = SpotifyCallbackRouteImport.update({
  id: '/spotify-callback',
  path: '/spotify-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsRoute = SongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchichtplanRoute = SchichtplanRouteImport.update({
  id: '/schichtplan',
  path: '/schichtplan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MusikRoute = MusikRouteImport.update({
  id: '/musik',
  path: '/musik',
  getParentRoute: () => rootRouteImport,
} as any)
const MitarbeiterRoute = MitarbeiterRouteImport.update({
  id: '/mitarbeiter',
  path: '/mitarbeiter',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSpotifyRoute = SettingsSpotifyRouteImport.update({
  id: '/spotify',
  path: '/spotify',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRegionRoute = SettingsRegionRouteImport.update({
  id: '/region',
  path: '/region',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRecipesRoute = SettingsRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsQrRoute = SettingsQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProductsRoute = SettingsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrintersRoute = SettingsPrintersRouteImport.update({
  id: '/printers',
  path: '/printers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMembersRoute = SettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLocationsRoute = SettingsLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsHappyHourRoute = SettingsHappyHourRouteImport.update({
  id: '/happy-hour',
  path: '/happy-hour',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDatabaseRoute = SettingsDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => SettingsRoute,
} as any)
const OrderTokenRoute = OrderTokenRouteImport.update({
  id: '/order/$token',
  path: '/order/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTokenPaidRoute = OrderTokenPaidRouteImport.update({
  id: '/paid',
  path: '/paid',
  getParentRoute: () => OrderTokenRoute,
} as any)
const ApiPublicSpotifySearchRoute = ApiPublicSpotifySearchRouteImport.update({
  id: '/api/public/spotify-search',
  path: '/api/public/spotify-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSongRequestRoute = ApiPublicSongRequestRouteImport.update({
  id: '/api/public/song-request',
  path: '/api/public/song-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicServiceCallRoute = ApiPublicServiceCallRouteImport.update({
  id: '/api/public/service-call',
  path: '/api/public/service-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentRequestRoute = ApiPublicPaymentRequestRouteImport.update({
  id: '/api/public/payment-request',
  path: '/api/public/payment-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrderRoute = ApiPublicOrderRouteImport.update({
  id: '/api/public/order',
  path: '/api/public/order',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTableTokenRoute = ApiPublicTableTokenRouteImport.update({
  id: '/api/public/table/$token',
  path: '/api/public/table/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsCreateTableCheckoutRoute =
  ApiPublicPaymentsCreateTableCheckoutRouteImport.update({
    id: '/api/public/payments/create-table-checkout',
    path: '/api/public/payments/create-table-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/kitchen': typeof KitchenRoute
  '/mitarbeiter': typeof MitarbeiterRoute
  '/musik': typeof MusikRoute
  '/payments': typeof PaymentsRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/schichtplan': typeof SchichtplanRoute
  '/settings': typeof SettingsRouteWithChildren
  '/songs': typeof SongsRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
  '/spotify-player': typeof SpotifyPlayerRoute
  '/staff': typeof StaffRoute
  '/tables': typeof TablesRoute
  '/order/$token': typeof OrderTokenRouteWithChildren
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/happy-hour': typeof SettingsHappyHourRoute
  '/settings/locations': typeof SettingsLocationsRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/printers': typeof SettingsPrintersRoute
  '/settings/products': typeof SettingsProductsRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/recipes': typeof SettingsRecipesRoute
  '/settings/region': typeof SettingsRegionRoute
  '/settings/spotify': typeof SettingsSpotifyRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/public/order': typeof ApiPublicOrderRoute
  '/api/public/payment-request': typeof ApiPublicPaymentRequestRoute
  '/api/public/service-call': typeof ApiPublicServiceCallRoute
  '/api/public/song-request': typeof ApiPublicSongRequestRoute
  '/api/public/spotify-search': typeof ApiPublicSpotifySearchRoute
  '/order/$token/paid': typeof OrderTokenPaidRoute
  '/api/public/payments/create-table-checkout': typeof ApiPublicPaymentsCreateTableCheckoutRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/table/$token': typeof ApiPublicTableTokenRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/kitchen': typeof KitchenRoute
  '/mitarbeiter': typeof MitarbeiterRoute
  '/musik': typeof MusikRoute
  '/payments': typeof PaymentsRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/schichtplan': typeof SchichtplanRoute
  '/songs': typeof SongsRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
  '/spotify-player': typeof SpotifyPlayerRoute
  '/staff': typeof StaffRoute
  '/tables': typeof TablesRoute
  '/order/$token': typeof OrderTokenRouteWithChildren
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/happy-hour': typeof SettingsHappyHourRoute
  '/settings/locations': typeof SettingsLocationsRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/printers': typeof SettingsPrintersRoute
  '/settings/products': typeof SettingsProductsRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/recipes': typeof SettingsRecipesRoute
  '/settings/region': typeof SettingsRegionRoute
  '/settings/spotify': typeof SettingsSpotifyRoute
  '/settings': typeof SettingsIndexRoute
  '/api/public/order': typeof ApiPublicOrderRoute
  '/api/public/payment-request': typeof ApiPublicPaymentRequestRoute
  '/api/public/service-call': typeof ApiPublicServiceCallRoute
  '/api/public/song-request': typeof ApiPublicSongRequestRoute
  '/api/public/spotify-search': typeof ApiPublicSpotifySearchRoute
  '/order/$token/paid': typeof OrderTokenPaidRoute
  '/api/public/payments/create-table-checkout': typeof ApiPublicPaymentsCreateTableCheckoutRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/table/$token': typeof ApiPublicTableTokenRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/kitchen': typeof KitchenRoute
  '/mitarbeiter': typeof MitarbeiterRoute
  '/musik': typeof MusikRoute
  '/payments': typeof PaymentsRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/schichtplan': typeof SchichtplanRoute
  '/settings': typeof SettingsRouteWithChildren
  '/songs': typeof SongsRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
  '/spotify-player': typeof SpotifyPlayerRoute
  '/staff': typeof StaffRoute
  '/tables': typeof TablesRoute
  '/order/$token': typeof OrderTokenRouteWithChildren
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/happy-hour': typeof SettingsHappyHourRoute
  '/settings/locations': typeof SettingsLocationsRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/printers': typeof SettingsPrintersRoute
  '/settings/products': typeof SettingsProductsRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/recipes': typeof SettingsRecipesRoute
  '/settings/region': typeof SettingsRegionRoute
  '/settings/spotify': typeof SettingsSpotifyRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/public/order': typeof ApiPublicOrderRoute
  '/api/public/payment-request': typeof ApiPublicPaymentRequestRoute
  '/api/public/service-call': typeof ApiPublicServiceCallRoute
  '/api/public/song-request': typeof ApiPublicSongRequestRoute
  '/api/public/spotify-search': typeof ApiPublicSpotifySearchRoute
  '/order/$token/paid': typeof OrderTokenPaidRoute
  '/api/public/payments/create-table-checkout': typeof ApiPublicPaymentsCreateTableCheckoutRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/table/$token': typeof ApiPublicTableTokenRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expenses'
    | '/inventory'
    | '/kitchen'
    | '/mitarbeiter'
    | '/musik'
    | '/payments'
    | '/pos'
    | '/reports'
    | '/schichtplan'
    | '/settings'
    | '/songs'
    | '/spotify-callback'
    | '/spotify-player'
    | '/staff'
    | '/tables'
    | '/order/$token'
    | '/settings/database'
    | '/settings/happy-hour'
    | '/settings/locations'
    | '/settings/members'
    | '/settings/printers'
    | '/settings/products'
    | '/settings/qr'
    | '/settings/recipes'
    | '/settings/region'
    | '/settings/spotify'
    | '/settings/'
    | '/api/public/order'
    | '/api/public/payment-request'
    | '/api/public/service-call'
    | '/api/public/song-request'
    | '/api/public/spotify-search'
    | '/order/$token/paid'
    | '/api/public/payments/create-table-checkout'
    | '/api/public/payments/webhook'
    | '/api/public/table/$token'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expenses'
    | '/inventory'
    | '/kitchen'
    | '/mitarbeiter'
    | '/musik'
    | '/payments'
    | '/pos'
    | '/reports'
    | '/schichtplan'
    | '/songs'
    | '/spotify-callback'
    | '/spotify-player'
    | '/staff'
    | '/tables'
    | '/order/$token'
    | '/settings/database'
    | '/settings/happy-hour'
    | '/settings/locations'
    | '/settings/members'
    | '/settings/printers'
    | '/settings/products'
    | '/settings/qr'
    | '/settings/recipes'
    | '/settings/region'
    | '/settings/spotify'
    | '/settings'
    | '/api/public/order'
    | '/api/public/payment-request'
    | '/api/public/service-call'
    | '/api/public/song-request'
    | '/api/public/spotify-search'
    | '/order/$token/paid'
    | '/api/public/payments/create-table-checkout'
    | '/api/public/payments/webhook'
    | '/api/public/table/$token'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/expenses'
    | '/inventory'
    | '/kitchen'
    | '/mitarbeiter'
    | '/musik'
    | '/payments'
    | '/pos'
    | '/reports'
    | '/schichtplan'
    | '/settings'
    | '/songs'
    | '/spotify-callback'
    | '/spotify-player'
    | '/staff'
    | '/tables'
    | '/order/$token'
    | '/settings/database'
    | '/settings/happy-hour'
    | '/settings/locations'
    | '/settings/members'
    | '/settings/printers'
    | '/settings/products'
    | '/settings/qr'
    | '/settings/recipes'
    | '/settings/region'
    | '/settings/spotify'
    | '/settings/'
    | '/api/public/order'
    | '/api/public/payment-request'
    | '/api/public/service-call'
    | '/api/public/song-request'
    | '/api/public/spotify-search'
    | '/order/$token/paid'
    | '/api/public/payments/create-table-checkout'
    | '/api/public/payments/webhook'
    | '/api/public/table/$token'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpensesRoute: typeof ExpensesRoute
  InventoryRoute: typeof InventoryRoute
  KitchenRoute: typeof KitchenRoute
  MitarbeiterRoute: typeof MitarbeiterRoute
  MusikRoute: typeof MusikRoute
  PaymentsRoute: typeof PaymentsRoute
  PosRoute: typeof PosRoute
  ReportsRoute: typeof ReportsRoute
  SchichtplanRoute: typeof SchichtplanRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SongsRoute: typeof SongsRoute
  SpotifyCallbackRoute: typeof SpotifyCallbackRoute
  SpotifyPlayerRoute: typeof SpotifyPlayerRoute
  StaffRoute: typeof StaffRoute
  TablesRoute: typeof TablesRoute
  OrderTokenRoute: typeof OrderTokenRouteWithChildren
  ApiPublicOrderRoute: typeof ApiPublicOrderRoute
  ApiPublicPaymentRequestRoute: typeof ApiPublicPaymentRequestRoute
  ApiPublicServiceCallRoute: typeof ApiPublicServiceCallRoute
  ApiPublicSongRequestRoute: typeof ApiPublicSongRequestRoute
  ApiPublicSpotifySearchRoute: typeof ApiPublicSpotifySearchRoute
  ApiPublicPaymentsCreateTableCheckoutRoute: typeof ApiPublicPaymentsCreateTableCheckoutRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicTableTokenRoute: typeof ApiPublicTableTokenRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotify-player': {
      id: '/spotify-player'
      path: '/spotify-player'
      fullPath: '/spotify-player'
      preLoaderRoute: typeof SpotifyPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotify-callback': {
      id: '/spotify-callback'
      path: '/spotify-callback'
      fullPath: '/spotify-callback'
      preLoaderRoute: typeof SpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs': {
      id: '/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schichtplan': {
      id: '/schichtplan'
      path: '/schichtplan'
      fullPath: '/schichtplan'
      preLoaderRoute: typeof SchichtplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musik': {
      id: '/musik'
      path: '/musik'
      fullPath: '/musik'
      preLoaderRoute: typeof MusikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitarbeiter': {
      id: '/mitarbeiter'
      path: '/mitarbeiter'
      fullPath: '/mitarbeiter'
      preLoaderRoute: typeof MitarbeiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/spotify': {
      id: '/settings/spotify'
      path: '/spotify'
      fullPath: '/settings/spotify'
      preLoaderRoute: typeof SettingsSpotifyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/region': {
      id: '/settings/region'
      path: '/region'
      fullPath: '/settings/region'
      preLoaderRoute: typeof SettingsRegionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/recipes': {
      id: '/settings/recipes'
      path: '/recipes'
      fullPath: '/settings/recipes'
      preLoaderRoute: typeof SettingsRecipesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/qr': {
      id: '/settings/qr'
      path: '/qr'
      fullPath: '/settings/qr'
      preLoaderRoute: typeof SettingsQrRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/products': {
      id: '/settings/products'
      path: '/products'
      fullPath: '/settings/products'
      preLoaderRoute: typeof SettingsProductsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/printers': {
      id: '/settings/printers'
      path: '/printers'
      fullPath: '/settings/printers'
      preLoaderRoute: typeof SettingsPrintersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/members': {
      id: '/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof SettingsMembersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/locations': {
      id: '/settings/locations'
      path: '/locations'
      fullPath: '/settings/locations'
      preLoaderRoute: typeof SettingsLocationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/happy-hour': {
      id: '/settings/happy-hour'
      path: '/happy-hour'
      fullPath: '/settings/happy-hour'
      preLoaderRoute: typeof SettingsHappyHourRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/database': {
      id: '/settings/database'
      path: '/database'
      fullPath: '/settings/database'
      preLoaderRoute: typeof SettingsDatabaseRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/order/$token': {
      id: '/order/$token'
      path: '/order/$token'
      fullPath: '/order/$token'
      preLoaderRoute: typeof OrderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$token/paid': {
      id: '/order/$token/paid'
      path: '/paid'
      fullPath: '/order/$token/paid'
      preLoaderRoute: typeof OrderTokenPaidRouteImport
      parentRoute: typeof OrderTokenRoute
    }
    '/api/public/spotify-search': {
      id: '/api/public/spotify-search'
      path: '/api/public/spotify-search'
      fullPath: '/api/public/spotify-search'
      preLoaderRoute: typeof ApiPublicSpotifySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/song-request': {
      id: '/api/public/song-request'
      path: '/api/public/song-request'
      fullPath: '/api/public/song-request'
      preLoaderRoute: typeof ApiPublicSongRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/service-call': {
      id: '/api/public/service-call'
      path: '/api/public/service-call'
      fullPath: '/api/public/service-call'
      preLoaderRoute: typeof ApiPublicServiceCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-request': {
      id: '/api/public/payment-request'
      path: '/api/public/payment-request'
      fullPath: '/api/public/payment-request'
      preLoaderRoute: typeof ApiPublicPaymentRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/order': {
      id: '/api/public/order'
      path: '/api/public/order'
      fullPath: '/api/public/order'
      preLoaderRoute: typeof ApiPublicOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/table/$token': {
      id: '/api/public/table/$token'
      path: '/api/public/table/$token'
      fullPath: '/api/public/table/$token'
      preLoaderRoute: typeof ApiPublicTableTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/create-table-checkout': {
      id: '/api/public/payments/create-table-checkout'
      path: '/api/public/payments/create-table-checkout'
      fullPath: '/api/public/payments/create-table-checkout'
      preLoaderRoute: typeof ApiPublicPaymentsCreateTableCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsDatabaseRoute: typeof SettingsDatabaseRoute
  SettingsHappyHourRoute: typeof SettingsHappyHourRoute
  SettingsLocationsRoute: typeof SettingsLocationsRoute
  SettingsMembersRoute: typeof SettingsMembersRoute
  SettingsPrintersRoute: typeof SettingsPrintersRoute
  SettingsProductsRoute: typeof SettingsProductsRoute
  SettingsQrRoute: typeof SettingsQrRoute
  SettingsRecipesRoute: typeof SettingsRecipesRoute
  SettingsRegionRoute: typeof SettingsRegionRoute
  SettingsSpotifyRoute: typeof SettingsSpotifyRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsDatabaseRoute: SettingsDatabaseRoute,
  SettingsHappyHourRoute: SettingsHappyHourRoute,
  SettingsLocationsRoute: SettingsLocationsRoute,
  SettingsMembersRoute: SettingsMembersRoute,
  SettingsPrintersRoute: SettingsPrintersRoute,
  SettingsProductsRoute: SettingsProductsRoute,
  SettingsQrRoute: SettingsQrRoute,
  SettingsRecipesRoute: SettingsRecipesRoute,
  SettingsRegionRoute: SettingsRegionRoute,
  SettingsSpotifyRoute: SettingsSpotifyRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface OrderTokenRouteChildren {
  OrderTokenPaidRoute: typeof OrderTokenPaidRoute
}

const OrderTokenRouteChildren: OrderTokenRouteChildren = {
  OrderTokenPaidRoute: OrderTokenPaidRoute,
}

const OrderTokenRouteWithChildren = OrderTokenRoute._addFileChildren(
  OrderTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpensesRoute: ExpensesRoute,
  InventoryRoute: InventoryRoute,
  KitchenRoute: KitchenRoute,
  MitarbeiterRoute: MitarbeiterRoute,
  MusikRoute: MusikRoute,
  PaymentsRoute: PaymentsRoute,
  PosRoute: PosRoute,
  ReportsRoute: ReportsRoute,
  SchichtplanRoute: SchichtplanRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SongsRoute: SongsRoute,
  SpotifyCallbackRoute: SpotifyCallbackRoute,
  SpotifyPlayerRoute: SpotifyPlayerRoute,
  StaffRoute: StaffRoute,
  TablesRoute: TablesRoute,
  OrderTokenRoute: OrderTokenRouteWithChildren,
  ApiPublicOrderRoute: ApiPublicOrderRoute,
  ApiPublicPaymentRequestRoute: ApiPublicPaymentRequestRoute,
  ApiPublicServiceCallRoute: ApiPublicServiceCallRoute,
  ApiPublicSongRequestRoute: ApiPublicSongRequestRoute,
  ApiPublicSpotifySearchRoute: ApiPublicSpotifySearchRoute,
  ApiPublicPaymentsCreateTableCheckoutRoute:
    ApiPublicPaymentsCreateTableCheckoutRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicTableTokenRoute: ApiPublicTableTokenRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
