INSERT INTO public.products (id, name, category, price, description, active, sort_order)
SELECT gen_random_uuid()::text, v.name, v.category, v.price, v.description, v.active, v.sort_order
FROM (VALUES
('hausgemachte Joghurtsosse','Beilagen',1,null,true,101),
('warme Brötli','Beilagen',6,null,true,102),
('hausgemachte Knoblauchsosse','Beilagen',1,null,true,103),
('hausgemachte Peperoncini in Olivenöl','Beilagen',1,null,true,104),
('hausgemachte Cocktailsosse','Beilagen',1,null,true,105),
('hausgemachte  Tartarsosse','Beilagen',1,null,true,106),
('Gemischter Salat','Salate',8,null,true,107),
('Grüner Salat','Salate',7,null,true,108),
('Insalata Caprese','Salate',9,null,true,109),
('Griechischer Salat','Salate',12,'Grüner Salat mit Tomaten, Fetakäse, Gurken, Oliven und Zwiebeln.',true,110),
('Wurstkäsesalat','Salate',10,null,true,111),
('Thonsalat','Salate',10,null,true,112),
('Rucola Salat mit Parmesan','Salate',10,null,true,113),
('Tomatensalat','Salate',9,null,true,114),
('Crevetten Cocktail','Salate',15,null,true,115),
('Knoblibrot','Vorspeisen',9,'Mozzarella und Knoblauch',true,116),
('Portion Pommes Frittes','Vorspeisen',7,null,true,117),
('Lahmacun','Vorspeisen',18,null,true,118),
('Dönerbox - klein','Kebabgerichte',16,'Mit hausgemachten Saucen',true,119),
('Dönerbox - grosse','Kebabgerichte',26,'Mit hausgemachten Saucen',true,120),
('Cevapebox - klein','Kebabgerichte',15,'Mit hausgemachten Saucen',true,121),
('Cevapebox - grosse','Kebabgerichte',25,'Mit hausgemachten Saucen',true,122),
('Dönerbox - XXL','Kebabgerichte',36,null,true,123),
('Falafalbox - klein','Kebabgerichte',16,null,true,124),
('Pasta Bolognese','Pasta',23,'Tomatensauce mit Rindshackfleisch. Wird mit eine Nudelsorte nach Wahl zubereitet.',true,125),
('Pasta Piratino','Pasta',21,'Kalbfleisch, Zwiebeln, Knoblauch, Peperoncini und Rahm. Wird mit eine Nudelsorte nach Wahl zubereitet.',true,126),
('Pasta Carbonara','Pasta',18,'Speck, Eigelb und Rahmsauce. Wird mit eine Nudelsorte nach Wahl zubereitet.',true,127),
('Pasta Ai Funghi Porcini','Pasta',24,'Rahmsauce mit Steinpilzen, Knoblauch und Zwiebeln. Wird mit eine Nudelsorte nach Wahl zubereitet.',true,128),
('Pasta All`Arrabbiata','Pasta',21,'Tomatensauce, Peperoncini und Knoblauch. Wird mit eine Nudelsorte nach Wahl zubereitet.',true,129),
('Penne Al Forno','Pasta',24,'Schinken, Zwiebeln, Knoblauch, Tomatensauce mit Rahm und gratiniert.',true,130),
('Pasta Boscaiola','Pasta',19,'Rahmsauce mit verschiedenen Pilzen und Knoblauch. Wird mit eine Nudelsorte nach Wahl zubereitet.',true,131),
('Cannelloni (Vegetarisch)','Pasta',23,'Ricotta, Spinat- und Broccolifüllung',true,132),
('Lasagne','Pasta',23,'Mit Rindfleisch',true,133),
('Pasta Napoli','Pasta',16,'Tomatensauce. Wird mit eine Nudelsorte nach Wahl zubereitet.',true,134),
('Pasta Tiziana','Pasta',20,'Tomatensauce mit Rahm, Zwiebeln und Curry. Wird mit eine Nudelsorte nach Wahl zubereitet.',true,135),
('Cannelloni','Pasta',23,'Mit Rindfleischfüllung',true,136),
('Tortellini Alla Panna','Pasta',23,'Mit Rahmsauce',true,137),
('Pouletflügeli - 7 Stück','Fleisch, Fisch & Grill',25,'Mit 1 Beilagen',true,138),
('Cevapcici - 10 Stück','Fleisch, Fisch & Grill',27,'Mit 1 Beilagen',true,139),
('Fischknusperli - 8 Stück','Fleisch, Fisch & Grill',24,'Mit 1Beilagen',true,140),
('Schweinskotelett - 2 Stück','Fleisch, Fisch & Grill',29,'Mit 1 Beilagen',true,141),
('Chicken Nuggets - Kids','Fleisch, Fisch & Grill',13,'Kinderportion',true,142),
('Rinds Entrecôte','Fleisch, Fisch & Grill',37,'Mit 1 Beilage',true,143),
('Calamares im Bierteig - 8 Stück','Fleisch, Fisch & Grill',24,'Mit 1 Beilagen',true,144),
('Pouletspiess - 3 Stück','Fleisch, Fisch & Grill',27,'Mit 1 Beilagen',true,145),
('Lammspiess - 3 Stück','Fleisch, Fisch & Grill',29,'Mit 1 Beilagen',true,146),
('Frutti di Mare Platte - Solo','Fleisch, Fisch & Grill',29.95,'Frutti di Mare Platte Solo: Muscheln, Oktopus, Garnelen, Crevetten auf Salat, verfeinert mit frischer Zitrone. Ein Meer an Genuss.',true,147),
('Frutti di Mare Platte - Family','Fleisch, Fisch & Grill',99.95,'Frutti di Mare Platte Family : Muscheln, Oktopus, Garnelen, Crevetten auf Salat, verfeinert mit frischer Zitrone. Ein Meer an Genuss.',true,148),
('Lamm Kotelett - 3 Stück','Fleisch, Fisch & Grill',29,'Mit 1 Beilagen',true,149),
('Frutti di Mare Platte - Duo','Fleisch, Fisch & Grill',59.95,'Frutti di Mare Platte Duo : Muscheln, Oktopus, Garnelen, Crevetten auf Salat, verfeinert mit frischer Zitrone. Ein Meer an Genuss.',true,150),
('Chickencurry mit Basmatireis','Fleisch, Fisch & Grill',27,null,true,151),
('Crevetten Curry mit Basmatireis','Fleisch, Fisch & Grill',29,null,true,152),
('Rindsbraten mit Basmatireis','Fleisch, Fisch & Grill',29,null,true,153),
('Zürcher Geschnetzeltes mit Pommes','Fleisch, Fisch & Grill',27,null,true,154),
('Pizza Salami (scharf) - 32cm','Pizza - 32cm',24,'Tomaten, Mozzarella, scharfe Salami, Oregano',true,155),
('Pizza Margherita - 32cm','Pizza - 32cm',19,'Tomaten, Mozzarella und Oregano',true,156),
('Pizza Kebab - 32cm','Pizza - 32cm',24,'Tomaten, Mozzarella, Kebabfleisch, Oregano',true,157),
('Pizza Prosciutto e Funghi - 32cm','Pizza - 32cm',24,'Tomaten, Mozzarella, Schinken, Champignons, Oregano',true,158),
('Pizza Da Arda - 32cm','Pizza - 32cm',26,'Tomaten, Mozzarella, Rohschinken, Mascarpone, Rucola, Oregano',true,159),
('Pizza Hawaii - 32cm','Pizza - 32cm',24,'Tomaten, Mozzarella, Schinken, Ananas, Oregano',true,160),
('Pizza O Sole Mio - 32cm','Pizza - 32cm',24,'Tomaten, Mozzarella, Thon, Zwiebeln, Oliven, Kapern, Oregano',true,161),
('Pizza Toscana (scharf) - 32cm','Pizza - 32cm',25,'Tomaten, Mozzarella, scharfe Salami, Speck, Peperoni, Champignons, Zwiebeln, Oregano',true,162),
('Pizza Prosciutto - 32cm','Pizza - 32cm',22,'Tomaten, Mozzarella, Schinken, Oregano',true,163),
('Pizza Quattro Stagioni - 32cm','Pizza - 32cm',25,'Tomaten, Mozzarella, Schinken, Artischocken, Peperoni, Oliven, Champignons, Oregano',true,164),
('Pizza Piratino - 32cm','Pizza - 32cm',25,'Tomaten, Mozzarella, Kalbfleisch, Oliven, Peperoncini, Knoblauch, Oregano',true,165),
('Pizza Padrone - 32cm','Pizza - 32cm',25,'Tomaten, Mozzarella, Kalbfleisch, Oregano',true,166),
('Pizza Vegetariana - 32cm','Pizza - 32cm',25,'Tomaten, Mozzarella, verschiedene Gemüse, Oregano',true,167),
('Pizza Napoli - 32cm','Pizza - 32cm',21,'Tomaten, Mozzarella, Sardellen, Kapern, Oregano',true,168),
('Pizza Pesto - 32cm','Pizza - 32cm',21,'Tomaten, Mozzarella, Pestosauce, Oregano',true,169),
('Pizza Da Reco - 32cm','Pizza - 32cm',26,'Tomaten, Mozzarella, Hackfleisch, Ei, Spinat, Gorgonzola, Speck, Oregano',true,170),
('Pizza Fiorentina - 32cm','Pizza - 32cm',24,'Tomaten, Mozzarella, Spinat, Ei, Knoblauch, Oregano',true,171),
('Pizza Funghi - 32cm','Pizza - 32cm',22,'Tomaten, Mozzarella, Champignons, Oregano',true,172),
('Pizza Salmone - 32cm','Pizza - 32cm',26,'Tomaten, Mozzarella, Lachs, Zwiebeln, Kapern, Oregano',true,173),
('Pizza Capricciosa - 32cm','Pizza - 32cm',24,'Tomaten, Mozzarella, Artischocken, Peperoni, Champignons, Oregano',true,174),
('Pizza Boscaiola - 32cm','Pizza - 32cm',24,'Tomaten, Mozzarella, Champignons, Steinpilze, Knoblauch, Oregano',true,175),
('Calzone (zugedeckt) - 32cm','Pizza - 32cm',24,'Tomaten, Mozzarella, Pilzen, Schinken, Ei, Oregano',true,176),
('Pizza Frutti di Mare - 32cm','Pizza - 32cm',25,'Tomaten, Mozzarella, Meeresfrüchte, Oregano',true,177),
('Pizza Contadino - 32cm','Pizza - 32cm',25,'Tomaten, Mozzarella, Gorgonzola, Rohschinken, Rucola, Oregano',true,178),
('Pizza Luca - 32cm','Pizza - 32cm',26,'Tomaten, Mozzarella, Auberginen, Parmesan, Rohschinken, Rucola, Cherrytomaten, Oregano',true,179),
('Calzone Puzzone (zugedeckt) - 32cm','Pizza - 32cm',21,'Mozzarella, Zwiebeln, Schinken, Gorgonzola, Pesto, Oregano',true,180),
('Pizza Fammy - 32cm','Pizza - 32cm',26,'Tomaten, Mozzarella, Salami, Rindfleisch, Steinpilze, Ei, Gorgonzola, Oregano',true,181),
('Pizza Vegana - 32cm','Pizza - 32cm',26,'Tomaten, Vegankäse und verschiedene Gemüse.',true,182),
('Pizza Da Esma - 32cm','Pizza - 32cm',26,'Tomaten, Mozzarella, Schinken, Salami, Speck, Auberginen, Champignons, Oregano',true,183),
('Pizza Inferno - 32cm','Pizza - 32cm',24,'Tomaten, Mozzarella, Oliven, Sardellen, Peperoncini, Oregano',true,184),
('Pizza Cipolla Peperoni - 32cm','Pizza - 32cm',22,'Tomaten, Mozzarella, Cherrytomaten, Zwiebeln, Peperoni, Oregano',true,185),
('Pizza Gorgonzola - 32cm','Pizza - 32cm',22,'Tomaten, Mozzarella, Gorgonzola, Oregano',true,186),
('Pizza Mediterranea - 32cm','Pizza - 32cm',26,'Tomaten, Mozzarella, Zwiebeln, Spinat, Crevetten, Oregano',true,187),
('Pizza Da Osi - 32cm','Pizza - 32cm',26,'Tomaten, Mozzarella, Salami, Spinat, Auberginen, Parmesan, Oregano',true,188),
('Pizza Zitella - 32cm','Pizza - 32cm',21,'Tomaten, Mozzarella, Knoblauch, Oliven, Oregano',true,189),
('Pizza Madras - 32cm','Pizza - 32cm',21,'Tomaten, Mozzarella, Ananas, Banane, Curry, Pouletgeschnetzeltes, Oregano',true,190),
('Calzone Special (zugedeckt) - 32cm','Pizza - 32cm',24,'Tomaten, Mozzarella, Spinat, Ei, Pesto, Gorgonzola, Champignons, Oregano',true,191),
('My Pizza - 32cm','Pizza - 32cm',28,'Stelle dir deine eigene Pizza zusammen mit deinen Lieblings Beilagen',true,192),
('Pizza Tre Formaggi - 32cm','Pizza - 32cm',24,'Tomaten, Mozzarella, 3 verschiedene Käsesorten, Oregano',true,193),
('Pizza Campagnola - 32cm','Pizza - 32cm',24,'Tomaten, Mozzarella, Mais, Speck, Zwiebeln, Oregano',true,194),
('Pizza Kapitan Hook - Kids','Kinder Pizza',16,'Tomaten, Mozzarella, Oregano',true,195),
('Pizza Peter Pan - Kids','Kinder Pizza',16,'Tomaten, Mozzarella, Schinken, Ananas, Oregano',true,196),
('Pizza Piratino - Kids','Kinder Pizza',17,'Tomaten, Mozzarella, Schinken, Pilze, Eier, Oregano',true,197),
('Pizza Salami (scharf) - 45cm','Pizza Grande - 45cm',43,'Tomaten, Mozzarella, scharfe Salami, Oregano',true,198),
('Pizza Funghi - 45cm','Pizza Grande - 45cm',39,'Tomaten, Mozzarella, Champignons, Oregano',true,199),
('Pizza Prosciutto e Funghi - 45cm','Pizza Grande - 45cm',43,'Tomaten, Mozzarella, Schinken, Champignons, Oregano',true,200),
('Pizza Frutti di Mare - 45cm','Pizza Grande - 45cm',45,'Tomaten, Mozzarella, Meeresfrüchte, Oregano',true,201),
('Pizza Da Arda - 45cm','Pizza Grande - 45cm',47,'Tomaten, Mozzarella, Rohschinken, Mascarpone, Rucola, Oregano',true,202),
('Pizza Fiorentina - 45cm','Pizza Grande - 45cm',43,'Tomaten, Mozzarella, Spinat, Ei, Knoblauch, Oregano',true,203),
('Pizza O Sole Mio - 45cm','Pizza Grande - 45cm',46,'Tomaten, Mozzarella, Thon, Zwiebeln, Oliven, Kapern, Oregano',true,204),
('Pizza Padrone - 45cm','Pizza Grande - 45cm',45,'Tomaten, Mozzarella, Kalbfleisch, Oregano',true,205),
('Pizza Madras - 45cm','Pizza Grande - 45cm',46,'Tomaten, Mozzarella, Ananas, Banane, Curry, Pouletgeschnetzeltes, Oregano',true,206),
('Calzone (zugedeckt) - 45cm','Pizza Grande - 45cm',43,'Tomaten, Mozzarella, Pilzen, Schinken, Ei, Oregano',true,207),
('Pizza Gorgonzola - 45cm','Pizza Grande - 45cm',39,'Tomaten, Mozzarella, Gorgonzola, Oregano',true,208),
('Pizza Vegetariana - 45cm','Pizza Grande - 45cm',45,'Tomaten, Mozzarella, verschiedene Gemüse, Oregano',true,209),
('Pizza Toscana (scharf) - 45cm','Pizza Grande - 45cm',45,'Tomaten, Mozzarella, scharfe Salami, Speck, Peperoni, Champignons, Zwiebeln, Oregano',true,210),
('Pizza Inferno - 45cm','Pizza Grande - 45cm',43,'Tomaten, Mozzarella, Oliven, Sardellen, Peperoncini, Oregano',true,211),
('Pizza Salmone - 45cm','Pizza Grande - 45cm',47,'Tomaten, Mozzarella, Lachs, Zwiebeln, Kapern, Oregano',true,212),
('Calzone Puzzone (zugedeckt) - 45cm','Pizza Grande - 45cm',44,'Mozzarella, Zwiebeln, Schinken, Gorgonzola, Pesto, Oregano',true,213),
('Pizza Vegana - 45cm','Pizza Grande - 45cm',47,'Tomaten, Vegankäse und verschiedene Gemüse.',true,214),
('Pizza Margherita - 45cm','Pizza Grande - 45cm',33,'Tomaten, Mozzarella und Oregano',true,215),
('Pizza Prosciutto - 45cm','Pizza Grande - 45cm',39,'Tomaten, Mozzarella, Schinken, Oregano',true,216),
('Pizza Kebab - 45cm','Pizza Grande - 45cm',43,'Tomaten, Mozzarella, Kebabfleisch, Oregano',true,217),
('Pizza Quattro Stagioni - 45cm','Pizza Grande - 45cm',45,'Tomaten, Mozzarella, Schinken, Artischocken, Peperoni, Oliven, Champignons, Oregano',true,218),
('Pizza Campagnola - 45cm','Pizza Grande - 45cm',43,'Tomaten, Mozzarella, Mais, Speck, Zwiebeln, Oregano',true,219),
('Pizza Da Reco - 45cm','Pizza Grande - 45cm',47,'Tomaten, Mozzarella, Hackfleisch, Ei, Spinat, Gorgonzola, Speck, Oregano',true,220),
('Pizza Boscaiola - 45cm','Pizza Grande - 45cm',43,'Tomaten, Mozzarella, Champignons, Steinpilze, Knoblauch, Oregano',true,221),
('Pizza Capricciosa - 45cm','Pizza Grande - 45cm',43,'Tomaten, Mozzarella, Artischocken, Peperoni, Champignons, Oregano',true,222),
('Pizza Fammy - 45cm','Pizza Grande - 45cm',47,'Tomaten, Mozzarella, Salami, Rindfleisch, Steinpilze, Ei, Gorgonzola, Oregano',true,223),
('Pizza Cipolla Peperoni - 45cm','Pizza Grande - 45cm',39,'Tomaten, Mozzarella, Cherrytomaten, Zwiebeln, Peperoni, Oregano',true,224),
('Pizza Napoli - 45cm','Pizza Grande - 45cm',37,'Tomaten, Mozzarella, Sardellen, Kapern, Oregano',true,225),
('Pizza Pesto - 45cm','Pizza Grande - 45cm',37,'Tomaten, Mozzarella, Pestosauce, Oregano',true,226),
('Pizza Piratino - 45cm','Pizza Grande - 45cm',45,'Tomaten, Mozzarella, Kalbfleisch, Oliven, Peperoncini, Knoblauch, Oregano',true,227),
('Pizza Hawaii - 45cm','Pizza Grande - 45cm',43,'Tomaten, Mozzarella, Schinken, Ananas, Oregano',true,228),
('Calzone Special (zugedeckt) - 45cm','Pizza Grande - 45cm',43,'Tomaten, Mozzarella, Spinat, Ei, Pesto, Gorgonzola, Champignons, Oregano',true,229),
('Pizza Contadino - 45cm','Pizza Grande - 45cm',45,'Tomaten, Mozzarella, Gorgonzola, Rohschinken, Rucola, Oregano',true,230),
('Pizza Da Esma - 45cm','Pizza Grande - 45cm',47,'Tomaten, Mozzarella, Schinken, Salami, Speck, Auberginen, Champignons, Oregano',true,231),
('Pizza Zitella - 45cm','Pizza Grande - 45cm',37,'Tomaten, Mozzarella, Knoblauch, Oliven, Oregano',true,232),
('Pizza Mediterranea - 45cm','Pizza Grande - 45cm',47,'Tomaten, Mozzarella, Zwiebeln, Spinat, Crevetten, Oregano',true,233),
('Pizza Tre Formaggi - 45cm','Pizza Grande - 45cm',43,'Tomaten, Mozzarella, 3 verschiedene Käsesorten, Oregano',true,234),
('Pizza Luca - 45cm','Pizza Grande - 45cm',47,'Tomaten, Mozzarella, Auberginen, Parmesan, Rohschinken, Rucola, Cherrytomaten, Oregano',true,235),
('Pizza Da Osi - 45cm','Pizza Grande - 45cm',47,'Tomaten, Mozzarella, Salami, Spinat, Auberginen, Parmesan, Oregano',true,236),
('My Pizza - 45cm','Pizza Grande - 45cm',57.95,'Stelle dir deine eigene Pizza zusammen mit deinen Lieblings Beilagen',true,237),
('Tiramisu','Desserts',12,null,true,238),
('Panna Cotta al caramello','Desserts',9.5,null,true,239),
('Meringa','Desserts',9.5,null,true,240),
('Tartufo al cioccolato','Desserts',9,null,true,241),
('Coppa al Limone di Sorrento','Desserts',10,null,true,242),
('Torta della nonna','Desserts',9,null,true,243),
('Torta macao','Desserts',9,null,true,244),
('Cheesecake','Desserts',9,null,true,245),
('Ricotta e pere','Desserts',8,null,true,246),
('Souffle al cioccolato','Desserts',8,null,true,247),
('Souffle al pistacchio','Desserts',8,null,true,248),
('Coppa Mandorle e amaetto','Desserts',8,null,true,249),
('Coppa Spagnola','Desserts',10,null,true,250),
('Coppa Cioccolato e Nocciola','Desserts',10,null,true,251),
('Coppa Crema e Pistacchio','Desserts',10,null,true,252),
('Coppa Cheesecake Monterosa','Desserts',10,null,true,253),
('Cip Cioc','Desserts',8,null,true,254),
('Pan Dan','Desserts',8,null,true,255),
('Pizza Margerita - 50cm','Pizza - 50cm',45,null,true,256),
('Pizza Napoli - 50cm','Pizza - 50cm',56,null,true,257),
('Pizza Pesto - 50cm','Pizza - 50cm',56,null,true,258),
('Pizza Prosciutto - 50cm','Pizza - 50cm',57,null,true,259),
('Pizza Funghi - 50cm','Pizza - 50cm',49,null,true,260),
('Pizza O Sole Mio - 50cm','Pizza - 50cm',56,null,true,261),
('Pizza Frutti di Mare - 50cm','Pizza - 50cm',55,null,true,262),
('Pizza da Arda - 50cm','Pizza - 50cm',57,null,true,263),
('Pizza Padrone - 50cm','Pizza - 50cm',55,null,true,264),
('Pizza Piratino - 50cm','Pizza - 50cm',55,null,true,265),
('Pizza Madras - 50cm','Pizza - 50cm',56,null,true,266),
('Calzone (zugedeckt) - 50cm','Pizza - 50cm',53,null,true,267),
('Pizza Gorgonzola - 50cm','Pizza - 50cm',44,null,true,268),
('Pizza Hawaii - 50cm','Pizza - 50cm',48,null,true,269),
('Pizza Vegeteriana - 50cm','Pizza - 50cm',50,null,true,270),
('Pizza Toscana (scharf) - 50cm','Pizza - 50cm',50,null,true,271),
('Pizza Capricciosa - 50cm','Pizza - 50cm',48,null,true,272),
('Calzone Special (zugedeckt) - 50cm','Pizza - 50cm',48,null,true,273),
('Pizza Inferno - 50cm','Pizza - 50cm',48,null,true,274),
('Pizza Fiorentina - 50cm','Pizza - 50cm',48,null,true,275),
('Pizza Salami (scharf) - 50cm','Pizza - 50cm',48,null,true,276),
('Pizza Contandino - 50cm','Pizza - 50cm',50,null,true,277),
('Pizza da Esma - 50cm','Pizza - 50cm',52,null,true,278),
('Pizza Salmone - 50cm','Pizza - 50cm',52,null,true,279),
('Pizza Da Reco - 50cm','Pizza - 50cm',52,null,true,280),
('Pizza Fammy - 50cm','Pizza - 50cm',52,null,true,281),
('Pizza Kebab - 50cm','Pizza - 50cm',48,null,true,282),
('Pizza Prosciutto e Funghi - 50cm','Pizza - 50cm',48,null,true,283),
('Pizza Zitella - 50cm','Pizza - 50cm',42,null,true,284),
('Pizza Cipolla Peperoni - 50cm','Pizza - 50cm',44,null,true,285),
('Pizza Mediterranea - 50cm','Pizza - 50cm',52,null,true,286),
('Calzone Puzzone (zugedeckt) - 50cm','Pizza - 50cm',49,null,true,287),
('Pizza Tre Formaggi - 50cm','Pizza - 50cm',48,null,true,288),
('Pizza Luca - 50cm','Pizza - 50cm',52,null,true,289),
('Pizza Vegana - 50cm','Pizza - 50cm',52,null,true,290),
('Pizza Quattro Stagioni - 50cm','Pizza - 50cm',50,null,true,291),
('Pizza Boscaiola - 50cm','Pizza - 50cm',48,null,true,292),
('Pizza Campagnola - 50cm','Pizza - 50cm',48,null,true,293),
('Pizza Da Osi - 50cm','Pizza - 50cm',52,null,true,294),
('My Pizza - 50cm','Pizza - 50cm',62.95,null,true,295)
) AS v(name, category, price, description, active, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM public.products p WHERE p.name = v.name);